### ISSUE TITLE
availability per day

### ISSUE THREAD

**Issue by wenyinggu** [dsi-principles-prog/midterm-wenyinggu#2]
"availabilty_365" column:How many days a year can this Airbnb apartment be available for customers to book. 
"calculated_host_listings_count" column:Total numbers of Airbnb apartment this host have in NYC. 

If you check the "calculated_host_listings_count" column you will find some "host" has 327 Airbnb aprtments listed online and they are all available 365 days a year. The reason for this is these "host" are agency. Therefore, those that are available for more than 350 days a year are more likelly run by agency, so they charge more. Those that are available for only a few days a year are private properties, so they are better value for money. 

input:dataframe, variable
output:availability per day 

What we have in "availability_365" column is the availability per year. What we want is the availability per day.
The expected output will be like this
<img width="291" alt="availability per day" src="https://user-images.githubusercontent.com/54039242/67703121-ebe08200-f980-11e9-8d13-853e1b5bcd4b.png">

(1) Complete the function in 30-feature-engineering
(2) Add the "availability_per_day" variables into 40-modelling in prepared data (simply delete#)
(3) Test the bound, use the verify() or assert() function the test the bound. Since it is the ratio of availablity per day so it should be in the range of [0,1]

**Comment by shiyaol** [comment]
added "availability_per_day" feature, closes #2
